name: Z:\MFSCreditScore\env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.12.12
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - asttokens==3.0.1
      - colorama==0.4.6
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - executing==2.2.1
      - ipykernel==7.1.0
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - matplotlib-inline==0.2.1
      - nest-asyncio==1.6.0
      - packaging==25.0
      - parso==0.8.5
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - pure-eval==0.2.3
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pyzmq==27.1.0
      - six==1.17.0
      - stack-data==0.6.3
      - tornado==6.5.2
      - traitlets==5.14.3
      - wcwidth==0.2.14
prefix: Z:\MFSCreditScore\env
